### ISSUE TITLE
Focus on parsing the vocab file first

### ISSUE THREAD

**Issue by jybluekim** [ajkim0630/tic-tac-toe#1]
Here is how you can start parsing files.

```

f = open("xxx", 'r')
for l in f: 
  l2 = l.rstrip()
  m = re.match(r".*TD>(.*)<\/TD", l2) 
  if m: # m will be True if there is something that matches above expression
    print (m.group(1)) # this will print what is in the original m expression
    # you can do more check and processing on m.group(1)

```

**Comment by ajkim0630** [comment]
i did

i have a dictionary that looks like 

{'abominable': ('very hateful, detestable', 'adjective'), 'abomination': ('anything greatly disliked or abhorred', 'noun'), 'aboriginal': ('original or indigenous to a place ', 'adjective'), 'abort': ('to miscarry, to bring forth something prematurely ', 'verb'), 'abortive': ('unsuccessful', 'adjective'), 'abound': ('to be plentiful, to be very prevalent, to overflow ', 'verb'), 'aboveboard': (' in open sight, without concealment, or deception  ', 'adjective'), 'abrade ': ('to rub or wear away', 'verb')}

**Comment by jybluekim** [comment]
This is pretty awesome. I would love to see the code in the repo.

**Comment by ajkim0630** [comment]
done
