### ISSUE TITLE
Dump your data in json file

### ISSUE THREAD

**Issue by jybluekim** [ajkim0630/tic-tac-toe#2]
Here is how you can take your python data structure and dump it on json.

```
import json

# hash is your dictionary 
json = json.dumps(hash)
f = open("xxx", 'w')
f.write(json)

#######

# maybe in a different file

f = open("xxx", 'r')
hash = json.load(f)
# now look into the hash 

```

**Comment by ajkim0630** [comment]
it says "AttributeError: 'str' object has no attribute 'load'"

**Comment by jybluekim** [comment]
Are you doing it from a different program? From one program, you write a json file (e.g. vocab.json) and from another program you read the vocab.json.

**Comment by ajkim0630** [comment]
I made a file called vocab.json and put 

f = open("vocab.py", 'r')
hash = json.load(f)

in it but it doesn't work

**Comment by jybluekim** [comment]
I don't think you understood.

File vocab_raw.py will read the raw file and write to vocab.json

Then....

File vocab_json.py will read the json file (vocab.json) and now do whatever you need to do. E.g. print 100 random words or whatever. 

Is this clear?

**Comment by ajkim0630** [comment]
done

**Comment by ajkim0630** [comment]
ok i fixed it and now i used 3 files 2 programs
