### ISSUE TITLE
Vocab: write a program that tracks how many words you know

### ISSUE THREAD

**Issue by jybluekim** [ajkim0630/tic-tac-toe#4]
Write a function that asks you multiple questions about words. 

E.g. for an adjective, pull random defns of 5 different adjectives and make 1-5 and have the user give a number. Once he/she gets it right, then add that info in a separate json file which has a list of known words. 

At any given time you can check this json file check progress. 

Enjoy~~

**Comment by ajkim0630** [comment]
done
