### ISSUE TITLE
Vocab: need more changes in "known words"

### ISSUE THREAD

**Issue by jybluekim** [ajkim0630/tic-tac-toe#5]
More comments on "known words" feature of vocab.

1. You should run off of vocab_json.py - you already parsed the file and put it in json file, why do you want to parse again??? So put if __name__ == "__main__" etc in that file and start making calls.

2. You should write it so that you run it multiple times and your code should "remember" the known words so it does not ask you again. At the beginning of each round you should print out how many out of 6k you "know" so far.

**Comment by jybluekim** [comment]
You should also have a default "game length" - i.e. when I launch your program, by default maybe you will get 5 tests.

**Comment by ajkim0630** [comment]
done
